### ISSUE TITLE
Add a rule to enforce a newline between the metadata and code

### ISSUE THREAD

**Issue by bradenhilton** [Yash-Singh1/eslint-plugin-userscripts#32]
I'm not sure if this is already possible by default in ESLint, I thought [`lines-around-comment`](https://eslint.org/docs/rules/lines-around-comment) might work but I'm not sure how to only enforce it for the metadata and not for regular comments. There is an `ignorePattern` but no `includePattern`.

I've outlined how I would expect it to work below.

## Correct ✔

```javascript
// ==UserScript==
// ...
// ==/UserScript==

console.log('Hello world');
```

## Incorrect ❌

```javascript
// ==UserScript==
// ...
// ==/UserScript==
console.log('Hello world');
```

---

EDIT: I think I've achieved it with the following in my `.eslintrc`:

```json
{
  "rules": {
    "lines-around-comment": [
      "error",
      {
        "afterLineComment": true,
        "ignorePattern": "^(?:(?!==\/UserScript==).)*$"
      }
    ]
  }
}
```

As I understand it though, ESLint will check every single comment to see if the RegEx matches, which seems inefficient. A more specific rule/check from this plugin could be useful in this case.

**Comment by Yash-Singh1** [comment]
Added new `metadata-spacing` rule
