### ISSUE TITLE
Suspicious `console.log`

### ISSUE THREAD

**Issue by nikolay-borzov** [Yash-Singh1/eslint-plugin-userscripts#63]
I've noticed extra output when running this plugin.

I believe it originates from: https://github.com/Yash-Singh1/eslint-plugin-userscripts/blob/588ee7071854fd2d0eb505c8e3cfabac4c3f854f/lib/rules/compat-grant.js#L38-L44

**Comment by Yash-Singh1** [comment]
Sorry, I think I left it behind when I was debugging earlier, I now added a commit fixing this.
