### ISSUE TITLE
Support node 19.x

### ISSUE THREAD

**Issue by atompkins** [Yash-Singh1/eslint-plugin-userscripts#70]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-userscripts@0.2.11',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.7.0', npm: '9.5.0' }
npm WARN EBADENGINE }

**Comment by Yash-Singh1** [comment]
Just created a release, should have landed in 0.2.12.
