### ISSUE TITLE
Handle/add option for empty lines in the userscript metadata

### ISSUE THREAD

**Issue by double-beep** [Yash-Singh1/eslint-plugin-userscripts#8]
Sometimes, the userscript metadata may be complex (e.g. multiple `@match`/`@exclude`/`@include` headers). In these cases, I like to leave some lines empty between particular headers, e.g.:

```
// ==UserScript==
// @name         Some name
// @namespace    ....
// @version      1.0.0
// @author       ...
// @contributor  ...
// @description  ...
// @license      GPL-3.0
//
// @include      ...
// @include      ...
// @run-at       document-start
// @grant        none

// @updateURL    ...
// @downloadURL  ...
// @homepageURL  ...
// @supportURL   ...
// ==/UserScript==
``` 

If I use an empty line, I get `eslint: userscripts/no-invalid-metadata - Code found between in metadata` and if I only add `//` I get `eslint: userscripts/no-invalid-metadata - Attributes should begin with @`. This behaviour should be disabled by default or, at least, an option must be added.

**Comment by Yash-Singh1** [comment]
This looks like a useful update. We would have to update the checks on the following lines:

https://github.com/Yash-Singh1/eslint-plugin-userscripts/blob/main/lib/rules/no-invalid-metadata.js#L52

https://github.com/Yash-Singh1/eslint-plugin-userscripts/blob/main/lib/rules/no-invalid-metadata.js#L66

And update `require-attribute-space-prefix` to recognize comments without any content. Do you want to submit a PR for this?
