### ISSUE TITLE
incorrect reporting of invalid @grant

### ISSUE THREAD

**Issue by leaumar** [Yash-Singh1/eslint-plugin-userscripts#82]
Hi. First off, I should ask if this is the ruleset used by the Tampermonkey editor. I assume it is but I can't be sure.

If it is, it seems to be falsely reporting an invalid `@grant` for me:
![image](https://github.com/Yash-Singh1/eslint-plugin-userscripts/assets/3950300/c8f0a2df-4410-460e-a3ae-d32501d71fa4) (screenshot)

My script uses `GM.xmlhttpRequest` (reported invalid) in the grant section and in the actual code, and it works just fine in TM.

I did a little test and the linting in the TM editor reports the following:
- GM.xmlhttpRequest ❌ 
- GM_xmlhttpRequest ✔️ 
- GM.xmlHttpRequest ✔️ 
- GM_xmlHttpRequest ❌ 

I'm trying to compare the greasemonkey and tampermonkey docs on this but they each describe either `GM.x` or `GM_x` style only so I can't compare them directly.

Maybe I should turn the question around and ask what's the accepted source of manager-agnostic truth on this?

Thanks

**Comment by leaumar** [comment]
Having said that, I'm testing my script again just to be sure, and while it worked fine before, now it suddenly doesn't anymore. I must've made a mistaken change somewhere to the permission/function name and not even realized. Gonna close this, sorry for the noise.

**Comment by Yash-Singh1** [comment]
> Hi. First off, I should ask if this is the ruleset used by the Tampermonkey editor. I assume it is but I can't be sure.

Yes, the Tampermonkey editor does use this ruleset for validation, however the Tampermonkey implementation is sometimes a little off or might use an older version of this plugin.

> I did a little test and the linting in the TM editor reports the following:
> 
> * GM.xmlhttpRequest ❌
> * GM_xmlhttpRequest ✔️
> * GM.xmlHttpRequest ✔️
> * GM_xmlHttpRequest ❌

I forgot what the exact reason was, pretty sure it was related to naming in userscript manager implementations, but the `GM.` always has an uppercase H while the `GM_` always has a lowercase h.

> Having said that, I'm testing my script again just to be sure, and while it worked fine before, now it suddenly doesn't anymore. I must've made a mistaken change somewhere to the permission/function name and not even realized. Gonna close this, sorry for the noise.

No worries!

**Comment by leaumar** [comment]
Found a source for the change earlier: https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
